apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: push-worker-scaler
spec:
  scaleTargetRef:
    name: push-worker-app
    kind: Deployment
  minReplicaCount: 0
  maxReplicaCount: 5
  pollingInterval: 15
  cooldownPeriod: 300
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
        scaleUp:
          stabilizationWindowSeconds: 0
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: proposal
        host: amqp://rabbitmq.default.svc.cluster.local:5672/
        mode: QueueLength
        value: "1"