apiVersion: apps/v1
kind: Deployment
metadata:
  name: push-worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: push-worker-app
  template:
    metadata:
      labels:
        app: push-worker-app
    spec:
      nodeSelector:
        agentpool: pushpool
      containers:
        - name: push-worker
          image: steakfisher1/brc-worker:latest
          securityContext:
            privileged: true
          env:
            - name: DOCKER_HOST
              value: "tcp://localhost:2375"  # Changed to use TCP instead of socket
          envFrom:
            - configMapRef:
                name: push-worker-config
            - secretRef:
                name: push-worker-secret
          ports:
            - containerPort: 5000

        - name: dind
          image: docker:dind
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""  # Disable TLS completely
          args:
            - "--host=tcp://0.0.0.0:2375"
            - "--storage-driver=overlay2"
