apiVersion: apps/v1
kind: Deployment
metadata:
  name: push-worker-app
spec:
  selector:
    matchLabels:
      app: push-worker-app
  template:
    metadata:
      labels:
        app: push-worker-app
    spec:
#      tolerations:
#        - key: "dedicated"
#          operator: "Equal"
#          value: "pushworker"
#          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                      - pushpool
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - push-worker-app
              topologyKey: "kubernetes.io/hostname"
#      priorityClassName: high-priority
      containers:
        - name: dind
          image: docker:dind
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          args:
            - "--host=tcp://0.0.0.0:2375"
            - "--storage-driver=overlay2"
          readinessProbe:
            exec:
              command: [ "sh", "-c", "docker info >/dev/null 2>&1" ]
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30

        - name: push-worker
          image: steakfisher1/brc-worker:latest
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              echo "Waiting for Docker daemon to be ready..."
              until docker info >/dev/null 2>&1; do
                echo "Docker daemon not ready yet, waiting..."
                sleep 5
              done
              echo "Docker daemon is ready! Starting application..."
              exec npm start
          securityContext:
            privileged: true
          env:
            - name: DOCKER_HOST
              value: "tcp://localhost:2375"
          envFrom:
            - configMapRef:
                name: push-worker-config
            - secretRef:
                name: push-worker-secret
          ports:
            - containerPort: 5000
